// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace TestOldWay
{
    public partial class Post
    {
        public Post()
        {
            PostTags = new HashSet<PostTag>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }

        public virtual ICollection<PostTag> PostTags { get; set; }
    }
}